### ISSUE TITLE
Cannot build with production flag in AppVeyor

### ISSUE THREAD

**Issue by simonjaeger** [simonjaeger/azure-bot-pack#16]
The solution file is referencing development files (map files). Which causes AppVeyor to fail when building.

**Comment by syedhassaanahmed** [comment]
Nice work with AppVeyor there!

We can also export the AppVeyor.yml file from the portal and place it in root to have Infra-as-Code and version control CI changes. When .yml file is there, AppVeyor ignores GUI settings.

**Comment by simonjaeger** [comment]
@syedhassaanahmed Agreed! Would like to but need to disregard the publishing profile for our own development. Can we partially expose the AppVeyor and complement it via GUI settings?
