### ISSUE TITLE
Add analytics for bot

### ISSUE THREAD

**Issue by simonjaeger** [simonjaeger/azure-bot-pack#5]

**Comment by syedhassaanahmed** [comment]
We could use [Ibex dashboard](https://github.com/CatalystCode/ibex-dashboard). It relies on `Application Insights` for telemetry.

**Comment by simonjaeger** [comment]
@syedhassaanahmed Thought about this as well. Let's have a look at this later on. Possible to integrate?

**Comment by syedhassaanahmed** [comment]
Yes, best way to get going is to include [this SDK](https://github.com/CatalystCode/botbuilder-instrumentation-cs) in the bot project, and add LUIS, Sentiment Analysis and Application Insights keys to the config. Ibex reads directly from App Insights.
